---
server:
  port: 8888
spring:
  cloud:
    config:
      server:        
        git:
          uri: https://github.com/raulhsj/pluralsight-spring-cloudconfig-wa-tolls
          search-paths:
            - 'station*'
          repos:
            perfProfile:
              pattern:
                - '*/perf'
              uri: https://github.com/raulhsj/pluralsight-spring-cloudconfig-perf
              search-paths:
                - 'station*'
